language: haskell

script:
  - cabal configure --enable-tests --enable-library-coverage
  - cabal build && cabal test

after_script:
  - cabal sandbox init
  - cabal install hpc-coveralls
  - .cabal-sandbox/bin/hpc-coveralls spec doctest
