dist: trusty


language: c


matrix:
  include:
    - env: CABALVER=1.22 GHCVER=7.10.1
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1], sources: [hvr-ghc]}}
    - env: CABALVER=head GHCVER=head
      addons: {apt: {packages: [cabal-install-head,ghc-head], sources: [hvr-ghc]}}

  allow_failures:
    - env: CABALVER=head GHCVER=head


before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - cabal update


script:
  - cabal configure --enable-tests --enable-library-coverage
  - cabal build && cabal test

after_script:
  - cabal sandbox init
  - cabal install hpc-coveralls
  - .cabal-sandbox/bin/hpc-coveralls spec doctest
